openapi: 3.2.0
info:
  title: Lucra Forge Health API
  description: See https://docs.lucrasports.com/lucra-sdk/sdks-and-apis for implementation details.
  version: '1.0'
  contact: {}
servers:
- url: /
  description: Current host
- url: https://forge.lucrasports.com
  description: Production
- url: https://forge.sandbox.lucrasports.com
  description: Sandbox
tags:
- name: Health
paths:
  /health:
    get:
      operationId: HealthController_check
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Health
      summary: Health controller check
      x-summary-source: derived
components:
  securitySchemes:
    X-Lucra-Api-Key:
      type: apiKey
      in: header
      name: X-Lucra-Api-Key
      description: API key for tenant authentication
